# gz topic, main simulation clock
- ros_topic_name: "clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Car steering topics
- ros_topic_name: "/prius_hybrid/cmd_vel"
  gz_topic_name: "/prius_hybrid/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/prius_hybrid/steering_odom"
  gz_topic_name: "/prius_hybrid/steering_odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/prius_hybrid/tf"
  gz_topic_name: "/prius_hybrid/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin
- ros_topic_name: "/prius_hybrid/scan"
  gz_topic_name: "/prius_hybrid/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/prius_hybrid/imu_raw"
  gz_topic_name: "/prius_hybrid/imu_raw"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

- ros_topic_name: "/prius_hybrid/mag_raw"
  gz_topic_name: "/prius_hybrid/mag_raw"
  ros_type_name: "sensor_msgs/msg/MagneticField"
  gz_type_name: "gz.msgs.Magnetometer"
  direction: GZ_TO_ROS

- ros_topic_name: "/prius_hybrid/gps_raw"
  gz_topic_name: "/prius_hybrid/gps_raw"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS

# Camera info
- ros_topic_name: "/prius_hybrid/front_camera/camera_info"
  gz_topic_name: "/prius_hybrid/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS